WebApp/Controllers/RateController.cs
using Core;
using IService.UseCasesInterfaces.Products;
using IService.UseCasesInterfaces.Rates;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace WebApp.Controllers
{
    public class RateController : Controller
    {
        private readonly IGetProductByIdUseCase getProductById;
        private readonly IGetRateListByProductIdUseCase getRateListByProductId;
        private readonly IAddRateUseCase addRate;
        private readonly IGetRateByIdUseCase getRate;
        private readonly IUpdateRateUseCase updateRate;
        private readonly IDeleteRateUseCase deleteRate;

        public RateController(
            IGetProductByIdUseCase getProductById,
            IGetRateListByProductIdUseCase getRateListByProductId,
            IAddRateUseCase addRate,
            IGetRateByIdUseCase getRate,
            IUpdateRateUseCase updateRate,
            IDeleteRateUseCase deleteRate
            )
        {
            this.getProductById = getProductById;
            this.getRateListByProductId = getRateListByProductId;
            this.addRate = addRate;
            this.getRate = getRate;
            this.updateRate = updateRate;
            this.deleteRate = deleteRate;
        }
        
        public ActionResult GetRatesPerProduct(int id)
        {
            ViewBag.productName = getProductById.Execute(id).Name;
            ViewBag.productId = id;
            var rates = getRateListByProductId.Execute(id);
            return View(rates);
        }

        // GET: RateController1/Create/2
        public ActionResult Create(int id)
        {
            ViewBag.ProductName = getProductById.Execute(id).Name;
            ViewBag.ProductId = id;
            return View();
        }

        // POST: RateController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rate rate)
        {
            if (ModelState.IsValid)
            {
                addRate.Execute(rate);
                return RedirectToAction("Index","Product");
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        // GET: RateController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View(getRate.Execute(id));
        }

        // POST: RateController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Rate rate)
        {
            if (ModelState.IsValid)
            {
                updateRate.Execute(rate);
                return RedirectToAction(nameof(GetRatesPerProduct), new { id = rate.ProductId });
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        // GET: RateController1/Delete/5
        public ActionResult Delete(int id , int productId)
        {
            ViewBag.productId = productId;
            return View(getRate.Execute(id));
        }

        // POST: RateController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id,string productId)
        {
            deleteRate.Execute(id);
            return RedirectToAction(nameof(GetRatesPerProduct), new { id = int.Parse(productId) });
        }
    }
}

WebApp/Views/Rate/Create.cshtml
@model Core.Rate

@{
    ViewData["Title"] = "Create";
    var productName = (string)ViewBag.ProductName;
    var productId = (int)ViewBag.ProductId;
}

<h1>Add Rate for @productName</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <input hidden asp-for="ProductId" value="@productId"/>
            <div class="form-group mb-2">
                <label class="control-label">Product Name</label>
                <input readonly asp-for="ProductName" value="@productName" class="form-control" />
            </div>
            <div class="form-group mb-2">
                <label asp-for="RateNum" class="control-label"></label>
                <input asp-for="RateNum" class="form-control" />
                <span asp-validation-for="RateNum" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <input type="submit" value="Add Rate" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Rate/Delete.cshtml
@model Core.Rate

@{
    ViewData["Title"] = "Delete";
    var productId = (int)ViewBag.productId;
}

<h3>Are you sure you want to delete this rate?</h3>
<br/>
<div class="card">
    <h5 class="card-header">@Html.DisplayFor(model => model.ProductName)</h5>
    <div class="card-body">
        <h5 class="card-title"> @Html.DisplayFor(model => model.RateNum)</h5>
        <p class="card-text">@Html.DisplayFor(model => model.Comment)</p>
        <form asp-action="Delete" asp-route-productId="@productId">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to Rate List", "GetRatesPerProduct", "Rate", new { id = productId })
        </form>
    </div>
</div>

WebApp/Views/Rate/Edit.cshtml
@model Core.Rate

@{
    ViewData["Title"] = "Edit";
    var productId = Model.ProductId;
}

<h1>Edit</h1>

<h4>Rate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden asp-for="ProductId" value="@productId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input readonly asp-for="ProductName" class="form-control" />
            </div>
            <div class="form-group mb-2">
                <label asp-for="RateNum" class="control-label"></label>
                <input asp-for="RateNum" class="form-control" />
                <span asp-validation-for="RateNum" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Rate/GetRatesPerProduct.cshtml
@model IEnumerable<Core.Rate>

@{
    ViewData["Title"] = "GetRatesPerProduct";
    var productName = (string)ViewBag.productName;
    var productId = (int)ViewBag.productId;
}

<p>
    <h2 class="ms-3">@productName</h2>
</p>

@foreach (var item in Model) {
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">
                @Html.DisplayNameFor(model => item.RateNum)  : @Html.DisplayFor(model => item.RateNum)
            </h5>
            <hr style="width:25%;"/>
            <p class="card-text">@Html.DisplayFor(model => item.Comment)</p>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "text-success" }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id ,productId = item.ProductId} ,new{@class="text-danger"})
        </div>
    </div>
}

@Html.ActionLink("Go Back To The Product Details", "Details","Product",new {id = productId} , new { @class = "ms-3"})